about_markup_styles
vchumack/team-hardcode pull request #9
Opened 2022-07-22 15:41 UTC by arohoza

Валерія, подивись, будь ласка.
Лиш немає бекграунду на десктоп.
Якщо все ок,  то я  додам його коли стягну нову папку з зображеннями.

Футер надішлю пізніше.

2022-07-22 16:05 UTC, vchumack commented on src/sass/_about.scss
> +        @media screen and (max-width:767px), (min-device-pixel-ratio: 2),
написала в телеге насчет этого момента. Оно точно работает при таком формате написания?

2022-07-22 16:07 UTC, vchumack requested changes
в телеге написала вопрос относительно оформления медиа бекграунда

2022-07-23 02:18 UTC, arohoza commented
Пофіксила медіа запит, тепер з вендорним префіксом. Протестила, обирає зображення  коректно.
Додала  футер. Поки не робила для нього верхній  падінг, щоб не  було конфлікту  з верхньою секцією.
В файлі зі змінними додала один колір, він потрібен  був на ховер для кнопки.

2022-07-23 12:36 UTC, vchumack approved these changes

2022-07-23 12:36 UTC, merged

2022-07-23 12:36 UTC, vchumack approved these changes